CONFIG_KEY_NAME = "config"
OUTPUT_KEY_NAME = "output"
PIPELINE_CONFIG_KEY_NAME = "pipeline_config"
EXTRACT_CONFIG_KEY_NAME = "extract_config"
TRANSFORM_CONFIG_KEY_NAME = "transform_config"
LOAD_CONFIG_KEY_NAME = "load_config"
EXTRACT_OUTPUT_KEY = "extract_output"
TRANSFORM_OUTPUT_KEY = "transform_output"
